### PR TITLE
Fix Optifine compact

### PR DESCRIPTION
**Pull request by HowardZHY**

### CODE REVIEW

**Comment by DeexCoding** [comment]
I don't like the fact that it's not the newest version of yarn, I'll still merge it tho.

**Comment by HowardZHY** [comment]
> I don't like the fact that it's not the newest version of yarn, I'll still merge it tho.

I can try to update to latest yarn someday

**Comment by HowardZHY** [comment]
go and merge it

**Comment by DeexCoding** [comment]
It does not work.
The redirect in ChunkRenderHelperImplMixin does not work, which I knew about, that's not the issue.
But RealmsNotificationsScreen wants a function called buttonsClear in init, because loom is broken, I can't generate the sources for that file, I don't know if rolling back to older yarn versions fix that, and that is why you did it in the first place.

**Comment by HowardZHY** [comment]
damn, seems like library server is down. can't build.

**Pull request merged**
